# Generated by Django 6.0.4 on 2026-06-04 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_item_type_orderitemapprover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='file',
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/attachments/', verbose_name='Fayl')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Asl fayl nomi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.order')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_order_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyruq ilovasi',
                'verbose_name_plural': 'Buyruq ilovalari',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rgan vaqti")),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilgan vaqti')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='orders.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_acknowledgments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ko'rish/Qabul holati",
                'verbose_name_plural': "Ko'rish/Qabul holatlari",
                'unique_together': {('item', 'user')},
            },
        ),
    ]
