# Generated by Django 6.0.4 on 2026-06-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitemacknowledgment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('IJRO', 'Ijro uchun'), ('KELISHISH', 'Kelishish uchun'), ('MALUMOT', "Ma'lumot uchun")], default='IJRO', max_length=20, verbose_name='Band turi'),
        ),
    ]
