# Generated by Django 6.0.4 on 2026-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_malumot_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_for_all',
            field=models.BooleanField(default=False, verbose_name='Hamma uchun (har bir ijrochiga alohida topshiriq)'),
        ),
    ]
