# Generated by Django 6.0.4 on 2026-04-22 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0002_add_task_organization_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignees', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name="Rahbar mas'ul"),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Asosiy ijrochi'),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignees', to='organizations.organization'),
        ),
    ]
