# Generated by Django 6.0.4 on 2026-04-23 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0003_assignee_primary_leader_org'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskorganizationtarget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignees', to='organizations.chair'),
        ),
        migrations.AddField(
            model_name='taskorganizationtarget',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_org_targets', to='organizations.chair'),
        ),
        migrations.AlterUniqueTogether(
            name='taskorganizationtarget',
            unique_together={('task', 'organization', 'department', 'chair')},
        ),
    ]
