# Generated by Django 6.0.4 on 2026-05-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_task_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskorganizationtarget',
            unique_together=set(),
        ),
    ]
