# Generated by Django 6.0.4 on 2026-05-06 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_taskorganizationtarget_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Majlis nomi')),
                ('meeting_type', models.CharField(choices=[('REKTORAT', 'Rektorat'), ('ILMIY', 'Ilmiy kengash')], max_length=20, verbose_name='Majlis turi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Topshiriqlar yaratilganmi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Majlis',
                'verbose_name_plural': 'Majlislar',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_number', models.PositiveIntegerField(verbose_name='Band raqami')),
                ('content', models.TextField(verbose_name='Topshiriq mazmuni')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.meeting')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_item', to='tasks.task', verbose_name='Yaratilgan topshiriq')),
            ],
            options={
                'verbose_name': 'Majlis bandi',
                'verbose_name_plural': 'Majlis bandlari',
                'ordering': ['band_number'],
                'unique_together': {('meeting', 'band_number')},
            },
        ),
    ]
