# Generated by Django 6.0.4 on 2026-05-06 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='meetings/files/', verbose_name='Umumiy fayl'),
        ),
        migrations.AddField(
            model_name='task',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.meeting', verbose_name='Majlis'),
        ),
    ]
