# Generated by Django 6.0.4 on 2026-05-06 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_meeting_file_and_task_meeting_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.meeting', verbose_name='Majlis'),
        ),
    ]
