# Generated by Django 6.0.4 on 2026-05-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_add_submitted_at_to_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('REKTORAT', 'Rektorat')], max_length=20, verbose_name='Majlis turi'),
        ),
        migrations.AlterField(
            model_name='recurringmeetingitem',
            name='meeting_type',
            field=models.CharField(choices=[('REKTORAT', 'Rektorat')], db_index=True, max_length=20, verbose_name='Majlis turi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('REKTORAT', "Rektorat topshirig'i"), ('FUNKSIONAL', 'Funksional topshiriq'), ('QOSHIMCHA', "Qo'shimcha topshiriq"), ('ILMIY_KENGASH', "Ilmiy kengash topshirig'i")], db_index=True, default='FUNKSIONAL', max_length=15),
        ),
    ]
