# Generated by Django 6.0.4 on 2026-06-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_meeting_meeting_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_malumot',
            field=models.BooleanField(default=False, verbose_name="Ma'lumot uchun"),
        ),
    ]
