# Generated by Django 6.0.4 on 2026-07-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_is_for_all'),
        ('tasks', '0014_add_is_malumot'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='for_all_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='for_all_tasks', to='orders.orderitem', verbose_name='Hamma uchun bandi'),
        ),
    ]
