# Generated by Django 6.0.4 on 2026-05-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userroleassignment_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroleassignment',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('INSTITUTE_LEADER', 'Institut Rahbari'), ('BRANCH_LEADER', 'Filial Rahbari'), ('DEPT_HEAD', "Bo'lim Boshlig'i"), ('CHAIR_HEAD', 'Kafedra Mudiri'), ('TASK_CONTROLLER', 'Topshiriq Nazoratchi'), ('SCIENTIFIC_COUNCIL_SECRETARY', 'Ilmiy kengash kotibi'), ('EMPLOYEE', 'Xodim')], db_index=True, max_length=30),
        ),
    ]
