# Generated by Django 6.0.4 on 2026-05-13 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_chair_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('is_outside_plan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='organizations.department')),
            ],
            options={
                'verbose_name': 'Kunlik hisobot',
                'verbose_name_plural': 'Kunlik hisobotlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='daily_reports/images/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plans.dailyreport')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='organizations.department')),
            ],
            options={
                'verbose_name': 'Haftalik hisobot',
                'verbose_name_plural': 'Haftalik hisobotlar',
                'ordering': ['-year', '-week_number'],
                'unique_together': {('department', 'year', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_report_extras', to=settings.AUTH_USER_MODEL)),
                ('weekly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='plans.weeklyreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportExtraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='weekly_reports/images/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plans.weeklyreportextra')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_plans', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plans', to='organizations.department')),
            ],
            options={
                'verbose_name': 'Yillik ish rejasi',
                'verbose_name_plural': 'Yillik ish rejalari',
                'ordering': ['-year'],
                'unique_together': {('department', 'year')},
            },
        ),
        migrations.CreateModel(
            name='WorkPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('content', models.TextField()),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Oylik'), ('YEARLY', 'Yil davomida')], default='YEARLY', max_length=10)),
                ('deadline_month', models.IntegerField(blank=True, choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')], null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('COMPLETED', 'Bajarildi')], default='PENDING', max_length=15)),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.workplan')),
            ],
            options={
                'verbose_name': 'Reja bandi',
                'verbose_name_plural': 'Reja bandlari',
                'ordering': ['order_number'],
            },
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='work_plan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='plans.workplanitem'),
        ),
    ]
