# Generated by Django 6.0.4 on 2026-05-13 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreportextra',
            name='is_outside_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyreportextra',
            name='work_plan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_extras', to='plans.workplanitem'),
        ),
    ]
