# Generated by Django 6.0.4 on 2026-05-14 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_weeklyreportextra_is_outside_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workplan',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workplan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Tasdiq kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], default='PENDING', max_length=10),
        ),
    ]
