# Generated by Django 6.0.4 on 2026-05-05 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_chair_linked_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairs', to='organizations.organization'),
        ),
    ]
