# Generated by Django 6.0.4 on 2026-05-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_chair_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_type',
            field=models.CharField(choices=[('REGULAR', "Oddiy Bo'lim"), ('TASK_CONTROL', "Topshiriqlar Bo'limi"), ('ORDER_CONTROL', "Buyruqlar Bo'limi")], db_index=True, default='REGULAR', max_length=20),
        ),
    ]
